# File alice.toml

[parity]
chain = "Validator-set-tutorial.json"
base_path = "alice"

[network]
port = 30303
#bootnodes = []

[rpc]
port = 8545
apis = ["eth","net"]
cors = ["https://remix.ethereum.org"]

[websockets]
disable = false
port = 8546
interface = "local"

#[account]
#unlock = [""]      # Alice's account to sign transactions from remix.
#password = [""]