# File node1.toml

[parity]
chain = "Validator-set-tutorial.json"
base_path = "node1"

[network]
port = 30301
#bootnodes = []

[rpc]
disable = true

[websockets]
disable = true

[account]
#password = [""]

[mining]
#engine_signer = ""
reseal_on_txs = "none"
force_sealing = true