# File node0.toml

[parity]
chain = "Validator-set-tutorial.json"
base_path = "node0"

[network]
port = 30300
#bootnodes = []

[rpc]
disable = true

[websockets]
disable = true

[account]
password = ["node0.pwd"]

[mining]
#engine_signer = ""
reseal_on_txs = "none"
force_sealing = true